# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Seleniumtests(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(5)
        self.base_url = "http://127.0.0.1:8000/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_seleniumtests(self):
        driver = self.driver
        driver.get(self.base_url)
        driver.find_element_by_css_selector("b").click()
        driver.find_element_by_id("id_first_name").clear()
        time.sleep(1)
        driver.find_element_by_id("id_first_name").send_keys("administrador")
        driver.find_element_by_id("id_last_name").clear()
        time.sleep(1)
        driver.find_element_by_id("id_last_name").send_keys("administrador")
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("admin@gmail.com")
        time.sleep(1)
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("23555555")
        time.sleep(1)
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("admin")
        time.sleep(1)
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("admin")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_css_selector("b").click()
        time.sleep(1)
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("paciente")
        time.sleep(1)
        driver.find_element_by_id("id_last_name").clear()
        driver.find_element_by_id("id_last_name").send_keys("paciente")
        time.sleep(1)
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("pac@gmail.com")
        time.sleep(1)
        Select(driver.find_element_by_id("id_rol")).select_by_visible_text("Paciente")
        time.sleep(1)
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("101022222")
        time.sleep(1)
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("paciente")
        time.sleep(1)
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("paciente")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_css_selector("b").click()
        time.sleep(1)
        driver.find_element_by_id("id_first_name").clear()
        driver.find_element_by_id("id_first_name").send_keys("medico")
        time.sleep(1)
        driver.find_element_by_id("id_last_name").clear()
        driver.find_element_by_id("id_last_name").send_keys("medico")
        time.sleep(1)
        driver.find_element_by_id("id_email").clear()
        driver.find_element_by_id("id_email").send_keys("med@gmail.com")
        time.sleep(1)
        Select(driver.find_element_by_id("id_rol")).select_by_visible_text("Medico")
        time.sleep(1)
        driver.find_element_by_id("id_ci").clear()
        driver.find_element_by_id("id_ci").send_keys("20000000")
        time.sleep(1)
        driver.find_element_by_id("id_username").clear()
        driver.find_element_by_id("id_username").send_keys("medico")
        time.sleep(1)
        driver.find_element_by_id("id_passw").clear()
        driver.find_element_by_id("id_passw").send_keys("medico")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("admin")
        time.sleep(1)
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("admin")
        time.sleep(1)
        driver.find_element_by_css_selector("input.btn.btn-default").click()
        time.sleep(1)
        driver.find_element_by_link_text("Gestionar Especializaciones").click()
        time.sleep(1)
        driver.find_element_by_css_selector("i.fa.fa-plus-circle").click()
        time.sleep(1)
        driver.find_element_by_id("id_nombre_especialidad").clear()
        driver.find_element_by_id("id_nombre_especialidad").send_keys("cardiologia")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_css_selector("i.fa.fa-plus-circle").click()
        time.sleep(1)
        driver.find_element_by_id("id_nombre_especialidad").clear()
        driver.find_element_by_id("id_nombre_especialidad").send_keys("pediatria")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_link_text("Gestionar Historias").click()
        time.sleep(1)
        driver.find_element_by_link_text("cardiologia").click()
        driver.find_element_by_css_selector("i.fa.fa-plus-circle").click()
        time.sleep(1)
        driver.find_element_by_id("id_pregunta").clear()
        driver.find_element_by_id("id_pregunta").send_keys("estado del corazon")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_css_selector("i.fa.fa-plus-circle").click()
        time.sleep(1)
        driver.find_element_by_id("id_pregunta").clear()
        driver.find_element_by_id("id_pregunta").send_keys("latidos")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        driver.find_element_by_name("obligatoria").click()
        driver.find_element_by_css_selector("button.btn").click()
        time.sleep(1)
        driver.find_element_by_link_text("Salir").click()
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("medico")
        time.sleep(1)
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("medico")
        time.sleep(1)
        driver.find_element_by_css_selector("input.btn.btn-default").click()
        driver.find_element_by_link_text(u"Historias Clínicas").click()
        time.sleep(1)
        driver.find_element_by_link_text("Nueva Historia").click()
        Select(driver.find_element_by_id("id_paciente")).select_by_visible_text("101022222 paciente paciente")
        time.sleep(1)
        driver.find_element_by_id("id_antecedentes_personales").clear()
        driver.find_element_by_id("id_antecedentes_personales").send_keys("bien")
        ime.sleep(1)
        driver.find_element_by_id("id_antecedentes_familiares").clear()
        driver.find_element_by_id("id_antecedentes_familiares").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_motivo_consulta").clear()
        driver.find_element_by_id("id_motivo_consulta").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_enfermedad_actual").clear()
        driver.find_element_by_id("id_enfermedad_actual").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_peso").clear()
        driver.find_element_by_id("id_peso").send_keys("55")
        driver.find_element_by_id("id_talla").clear()
        driver.find_element_by_id("id_talla").send_keys("66")
        time.sleep(1)
        driver.find_element_by_id("id_signos_vitales").clear()
        driver.find_element_by_id("id_signos_vitales").send_keys("biena")
        time.sleep(1)
        driver.find_element_by_id("id_piel").clear()
        driver.find_element_by_id("id_piel").send_keys("bien")
        driver.find_element_by_id("id_ojos").clear()
        driver.find_element_by_id("id_ojos").send_keys("bien")
        driver.find_element_by_id("id_fosas_nasales").clear()
        driver.find_element_by_id("id_fosas_nasales").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_conductos_auditivos").clear()
        driver.find_element_by_id("id_conductos_auditivos").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_cavidad_oral").clear()
        driver.find_element_by_id("id_cavidad_oral").send_keys("bien")
        driver.find_element_by_id("id_cuello").clear()
        driver.find_element_by_id("id_cuello").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_columna").clear()
        driver.find_element_by_id("id_columna").send_keys("bien")
        driver.find_element_by_id("id_torax").clear()
        driver.find_element_by_id("id_torax").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_abdomen").clear()
        driver.find_element_by_id("id_abdomen").send_keys("bien")
        driver.find_element_by_id("id_extremidades").clear()
        driver.find_element_by_id("id_extremidades").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_genitales").clear()
        driver.find_element_by_id("id_genitales").send_keys("bien")
        driver.find_element_by_css_selector("input[type=\"submit\"]").click()
        time.sleep(1)
        driver.find_element_by_link_text("101022222").click()
        time.sleep(1)
        driver.find_element_by_id("id_antecedentes_personales").clear()
        driver.find_element_by_id("id_antecedentes_personales").send_keys("mal")
        time.sleep(1)
        driver.find_element_by_css_selector("input[type=\"submit\"]").click()
        time.sleep(1)
        driver.find_element_by_link_text("101022222").click()
        driver.find_element_by_link_text(u"Historias Clínicas").click()
        time.sleep(1)
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), r"^¿Está seguro que desea eliminar esta historia[\s\S]$")
        driver.find_element_by_link_text("Historias Especialidad").click()
        time.sleep(1)
        driver.find_element_by_link_text("Nueva Historia").click()
        Select(driver.find_element_by_id("id_paciente")).select_by_visible_text("101022222 paciente paciente")
        time.sleep(1)
        Select(driver.find_element_by_id("id_especialidad")).select_by_visible_text("cardiologia")
        time.sleep(1)
        driver.find_element_by_css_selector("option[value=\"cardiologia\"]").click()
        time.sleep(1)
        driver.find_element_by_name("respuesta").clear()
        driver.find_element_by_name("respuesta").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_xpath("(//input[@name='respuesta'])[2]").clear()
        driver.find_element_by_xpath("(//input[@name='respuesta'])[2]").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("agregar_pregunta").click()
        time.sleep(1)
        driver.find_element_by_css_selector("h4 > input[name=\"pregunta\"]").clear()
        driver.find_element_by_css_selector("h4 > input[name=\"pregunta\"]").send_keys("presion sanguinea")
        time.sleep(1)
        driver.find_element_by_css_selector("h4 > input[name=\"respuesta\"]").clear()
        driver.find_element_by_css_selector("h4 > input[name=\"respuesta\"]").send_keys("bien")
        time.sleep(1)
        driver.find_element_by_id("id_submit").click()
        time.sleep(1)
        self.assertRegexpMatches(self.close_alert_and_get_its_text(), r"^¿Está seguro que desea eliminar esta historia[\s\S]$")
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
